version: "3.7"

x-logging:
  &logging
  driver: "json-file"
  options:
    max-file: "5"
    max-size: 10m

services:
  epic.timebomb.generator:
    image: epic_project1:prod
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    logging: *logging
    init: true
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - ../.env
