version: "3.7"

x-logging:
  &logging
  driver: "json-file"
  options:
    max-file: "5"
    max-size: 10m

services:
  epic_project1:
    image: epic.project1:dev
    tty: true
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
    volumes:
      - ../src/epic_timebomb_generator:/app/epic_timebomb_generator
      #- ../alembic:/app/alembic
      - ../test:/app/test

      # Mount poetry files to edit them from inside the container
      - ../pyproject.toml:/app/pyproject.toml
      - ../poetry.lock:/app/poetry.lock

    ports:
      - 8000:8000
    env_file:
      - ../.env.dev
    init: true
    command: sleep infinity
